# Generated by Django 4.0.3 on 2023-06-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_sesion',
            name='recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coaching_sessions.recurso'),
        ),
    ]
