# Generated by Django 4.0.3 on 2023-06-09 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_sessions', '0002_info_sesion_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_sesion',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 6, 9), verbose_name='Fecha Creación'),
        ),
    ]
